### ISSUE TITLE
Latch authorization is required in desktop client

### ISSUE THREAD

**Issue by bustikiller** [ElevenPaths/latch-plugin-owncloud#20]
Whenever a PC connected to Owncloud is started, synchronization does not continue until Latch is unlocked using a mobile application. This behavior becomes a bit annoying.

Proposal: Owncloud could manage two operations; one for the web login and another one for the desktop application.

**Comment by jaesga** [comment]
Hi, 

We will consider your suggestion with the UX department, we will include this feature in a further release in case it's needed. 

Thank you.
Javier.
